name: detodo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  simple_animations: ^5.2.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.1
  url_launcher: ^6.3.1
  http: ^1.4.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  sensors_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" # <-- Ruta de tu nuevo logo

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: PasseroOne
      fonts:
        - asset: assets/fonts/PasseroOne-Regular.ttf