// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH9bDhnOso2ZiolFzpOrAhILo6hr8yiCk',
    appId: '1:225070298552:web:9e35e98824877adb280b4d',
    messagingSenderId: '225070298552',
    projectId: 'detodo-40bb0',
    authDomain: 'detodo-40bb0.firebaseapp.com',
    storageBucket: 'detodo-40bb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKoNTIG1QKkpUBLO9qrS8_CmIhrMzoCao',
    appId: '1:225070298552:android:37b8c9c53508a546280b4d',
    messagingSenderId: '225070298552',
    projectId: 'detodo-40bb0',
    storageBucket: 'detodo-40bb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYhhZ5hl6pac79Hr1aYHr7b0MrZGZyBR4',
    appId: '1:225070298552:ios:a12f0f29a5414e3d280b4d',
    messagingSenderId: '225070298552',
    projectId: 'detodo-40bb0',
    storageBucket: 'detodo-40bb0.firebasestorage.app',
    iosBundleId: 'com.example.detodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYhhZ5hl6pac79Hr1aYHr7b0MrZGZyBR4',
    appId: '1:225070298552:ios:a12f0f29a5414e3d280b4d',
    messagingSenderId: '225070298552',
    projectId: 'detodo-40bb0',
    storageBucket: 'detodo-40bb0.firebasestorage.app',
    iosBundleId: 'com.example.detodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH9bDhnOso2ZiolFzpOrAhILo6hr8yiCk',
    appId: '1:225070298552:web:d576eff3c809d5ca280b4d',
    messagingSenderId: '225070298552',
    projectId: 'detodo-40bb0',
    authDomain: 'detodo-40bb0.firebaseapp.com',
    storageBucket: 'detodo-40bb0.firebasestorage.app',
  );
}
